export const SUPPORTED_LANGUAGES = ["ru", "en", "pl"];

const translations = {
  ru: {
    "telemetry.choose": "Выберите график",
    "spec.gpsTitle": "GPS · 25 Гц", "spec.gpsCopy": "GPS, GLONASS, Galileo, BeiDou", "spec.bleCopy": "iOS и Android", "spec.batteryCopy": "до 20 часов работы", "spec.usbCopy": "зарядка около 3 часов", "spec.accelTitle": "Акселерометр", "spec.gyroTitle": "Гироскоп", "spec.storageTitle": "Встроенная память", "spec.storageCopy": ">2 ч при 25 Гц", "spec.splashTitle": "Защита от брызг", "spec.splashCopy": "дождь и водный спорт",
    "landing.kicker": "ТЕЛЕМЕТРИЯ, КОТОРУЮ МОЖНО ИСПОЛЬЗОВАТЬ", "landing.title": "Каждый круг.", "landing.accent": "Разобран по данным.", "landing.copy": "LapTrace записывает GPS и перегрузки на трассе. После заезда приложение синхронизирует лог по Bluetooth, сравнивает круги и показывает, где осталось время.", "landing.cta": "Создать бесплатный аккаунт", "landing.demoCta": "Посмотреть пример лога", "landing.proofRate": "точная телеметрия", "landing.proofSensors": "траектория и нагрузки", "landing.proofSync": "без кабелей и файлов", "landing.demoKicker": "РЕАЛЬНЫЙ ПРИМЕР", "landing.demoTitle": "Один лог. Полная картина заезда.", "landing.demoCopy": "Демонстрационная сессия с Circuito di Viterbo показывает, как LapTrace превращает поток датчиков в понятное сравнение кругов.", "landing.bestLap": "Лучший круг", "landing.liveSpeed": "Скорость в точке", "landing.liveG": "Боковая нагрузка", "landing.liveDelta": "Текущая дельта", "landing.compareKicker": "СРАВНЕНИЕ КРУГОВ", "landing.compareTitle": "Где найдено время", "landing.aiKicker": "AI-РАЗБОР", "landing.aiTitle": "Динамический разбор", "landing.aiInsight": "На круге 6 скорость на выходе из T4 выше на 7 км/ч.", "landing.insightBrake": "В T1 круг 6 тормозит позже и сохраняет стабильную продольную нагрузку. Здесь начинается преимущество над кругом 5.", "landing.insightMid": "В средней секции траектория круга 6 ровнее: меньше коррекций и выше минимальная скорость в повороте.", "landing.insightExit": "На выходе из T4 скорость круга 6 выше. Более раннее открытие газа сохраняет преимущество до следующего торможения.", "landing.insightFinal": "В финальном секторе преимущество удерживается без лишнего риска: дельта стабилизируется перед линией финиша.", "landing.unlock": "Анализировать свои заезды",
    "landing.liveInsight": "На круге {lap} в этой точке разница скорости с кругом {other}: {speed} км/ч, накопленная дельта: {delta} с. Значения рассчитаны из реального лога Viterbo.", "landing.demoError": "Не удалось загрузить демонстрационный лог Viterbo.",
    "gate.kicker": "ЗАКРЫТЫЙ ДОСТУП", "gate.title": "Ваш гоночный гараж", "gate.copy": "Войдите или создайте аккаунт, чтобы подключать LapTrace, загружать телеметрию и анализировать заезды.", "gate.button": "Войти или зарегистрироваться",
    "account.kicker": "ОБЛАЧНЫЙ ГАРАЖ", "account.title": "Вход в LapTrace", "account.copy": "Войдите, чтобы открыть свои логи и подключить устройство.", "account.registerTitle": "Создать аккаунт", "account.registerCopy": "Зарегистрируйтесь, чтобы подключать LapTrace, сохранять логи и анализировать заезды.", "account.password": "Пароль", "account.confirmPassword": "Повторите пароль", "account.passwordMismatch": "Пароли не совпадают", "account.create": "Создать аккаунт", "account.working": "Подождите…", "account.signIn": "Войти", "account.register": "Регистрация", "account.signOut": "Выйти", "account.profile": "Ваш гараж", "account.logs": "В облаке: {count} логов", "account.saved": "Логи сохранены в облаке.", "account.confirm": "Проверьте email для подтверждения регистрации.", "account.notConfigured": "Облако ещё не настроено администратором.",
    "nav.analysis": "Анализ", "nav.logs": "База логов", "logsPage.kicker": "ОБЛАЧНЫЙ ГАРАЖ", "logsPage.title": "База ваших заездов", "logsPage.copy": "Все логи LapTrace, сохранённые в вашем аккаунте. Выберите заезд, чтобы открыть траекторию, круги и графики телеметрии.", "logsPage.back": "Вернуться к анализу", "logsPage.import": "Добавить лог", "logsPage.imported": "Лог добавлен в базу аккаунта.",
    "status.disconnected": "LapTrace не подключён", "status.searching": "Поиск LapTrace…", "status.connectFailed": "Подключение не выполнено",
    "hero.kicker": "АНАЛИЗ ПАМЯТИ LAPTRACE", "hero.title": "Лог с устройства.", "hero.accent": "Сразу в разбор.",
    "hero.copy": "Подключитесь после заезда, скачайте сохранённую телеметрию по Bluetooth и выберите нужную сессию. Файлы и ручной импорт не нужны.",
    "action.connect": "Подключить LapTrace", "action.disconnect": "Отключить LapTrace", "action.start": "Начать запись", "action.stop": "Остановить запись",
    "action.download": "Скачать сохранённые сессии", "action.cancel": "Отменить", "action.unlock": "Разблокировать",
    "device.gps": "GPS", "device.battery": "Батарея", "device.free": "Свободно", "device.memory": "память устройства",
    "device.used": "Занято памяти", "device.records": "Записей", "device.waiting": "ожидание данных", "device.satellites": "{count} спутников",
    "device.fix": "3D FIX", "device.noFix": "НЕТ FIX", "device.charging": "заряжается", "device.batteryPower": "от батареи", "device.inputVoltage": "входное напряжение",
    "memory.protected": "Память защищена кодом", "memory.code": "Код", "memory.remaining": "{records} записей · ~{time} при 25 Гц",
    "hint.initial": "Устройство должно быть включено, находиться рядом и не быть подключено к телефону.", "hint.mock": "Активен тестовый BLE-адаптер.",
    "summary.sessions": "Сессии", "summary.loadFirst": "сначала скачайте память", "summary.duration": "Длительность", "summary.selected": "выбранная сессия",
    "summary.maxSpeed": "Макс. скорость", "summary.frequency": "Частота", "unit.speed": "км/ч", "unit.hz": "Гц",
    "track.kicker": "ТРАЕКТОРИЯ", "track.empty": "Нет загруженной сессии", "track.slower": "медленнее", "track.faster": "быстрее", "track.canvasEmpty": "Здесь появится траектория из памяти LapTrace",
    "sessions.kicker": "ПАМЯТЬ УСТРОЙСТВА", "sessions.title": "Сохранённые сессии", "sessions.empty": "После загрузки здесь появятся отдельные записи.", "sessions.item": "Сессия {id}", "sessions.points": "{count} точек", "sessions.rename": "Переименовать", "sessions.delete": "Удалить", "sessions.renamePrompt": "Название заезда", "sessions.deleteConfirm": "Удалить «{title}» из облака?",
    "telemetry.kicker": "ТЕЛЕМЕТРИЯ", "telemetry.speed": "Скорость", "telemetry.gforce": "ПЕРЕГРУЗКИ", "telemetry.longitudinal": "Продольная перегрузка", "telemetry.lateral": "Боковая перегрузка", "insights.kicker": "ИНЖЕНЕРНЫЙ РАЗБОР", "insights.title": "Что видно в данных", "insights.empty": "Скачайте лог с LapTrace, чтобы получить первичный разбор.",
    "laps.kicker": "КРУГИ", "laps.compareTitle": "Сравнение кругов", "laps.primary": "Основной круг", "laps.compare": "Сравнить с", "laps.none": "Без сравнения", "laps.option": "Круг {lap} · {time}", "laps.legend": "Круг {lap}",
    "ai.title": "Контекст для AI-инженера", "ai.copy": "Приложение агрегирует выбранную BLE-сессию: скорость, нагрузки, качество GPS и временную структуру. Сырой поток остаётся локально.",
    "ai.placeholder": "Например: какие три особенности этой сессии стоит проверить?", "ai.button": "Скопировать AI-контекст", "ai.first": "Сначала скачайте и выберите сессию.", "footer.noData": "Нет данных",
    "progress.preparing": "Подготовка…", "progress.records": "{received} / {expected} записей", "progress.done": "Готово: {count} сесс.",
    "state.connected": "{name} · подключён", "state.ready": "{name} · готов", "state.reading": "{name} · чтение памяти", "state.downloading": "{name} · загрузка", "state.loaded": "{name} · данные загружены",
    "state.recording": "{name} · идёт запись", "state.stopped": "{name} · запись остановлена", "hint.recording": "Запись идёт во внутреннюю память устройства.", "hint.ready": "Память готова. Модель: {model}.",
    "error.notSelected": "Устройство не выбрано. Включите LapTrace, закройте его приложение на телефоне и выберите LapTrace в списке BLE-устройств.",
    "error.network": "Не удалось установить BLE-соединение. LapTrace может быть подключён к телефону или другому приложению.", "error.security": "Браузер заблокировал Bluetooth. Откройте приложение в Chrome или Edge по адресу localhost.",
    "insight.fastest": "Лучший круг — №{lap}; разброс до самого медленного круга составляет {delta} с.", "insight.braking": "Самое сильное продольное замедление на круге №{lap}: {value} g. Знак зависит от ориентации устройства.", "insight.lateral": "Пиковая боковая нагрузка — {value} g на круге №{lap}.", "insight.qualityGood": "Поток ровный: {hz} Гц, разрывов длиннее {gap} мс не обнаружено.", "insight.qualityBad": "Обнаружено {count} разрывов потока; проверьте качество записи.",
  },
  en: {
    "telemetry.choose": "Choose chart",
    "spec.gpsTitle": "GPS · 25 Hz", "spec.gpsCopy": "GPS, GLONASS, Galileo, BeiDou", "spec.bleCopy": "iOS and Android", "spec.batteryCopy": "up to 20 hours use", "spec.usbCopy": "about 3 hours charging", "spec.accelTitle": "Accelerometer", "spec.gyroTitle": "Gyroscope", "spec.storageTitle": "Internal storage", "spec.storageCopy": ">2 h at 25 Hz", "spec.splashTitle": "Splash resistant", "spec.splashCopy": "rain and water sports",
    "landing.kicker": "TELEMETRY YOU CAN ACT ON", "landing.title": "Every lap.", "landing.accent": "Explained by data.", "landing.copy": "LapTrace records GPS and G-forces on track. After the run, the app syncs the log over Bluetooth, compares laps, and shows where time was left.", "landing.cta": "Create a free account", "landing.demoCta": "Explore a sample log", "landing.proofRate": "precision telemetry", "landing.proofSensors": "line and vehicle loads", "landing.proofSync": "no cables or files", "landing.demoKicker": "REAL SESSION EXAMPLE", "landing.demoTitle": "One log. The complete run.", "landing.demoCopy": "This Circuito di Viterbo demo shows how LapTrace turns a sensor stream into a clear, actionable lap comparison.", "landing.bestLap": "Best lap", "landing.liveSpeed": "Speed at cursor", "landing.liveG": "Lateral load", "landing.liveDelta": "Live delta", "landing.compareKicker": "LAP COMPARISON", "landing.compareTitle": "Where the time was found", "landing.aiKicker": "AI REVIEW", "landing.aiTitle": "Dynamic session review", "landing.aiInsight": "Lap 6 carries more speed out of T4.", "landing.insightBrake": "Into T1, lap 6 brakes later while keeping longitudinal load stable. The advantage over lap 5 starts here.", "landing.insightMid": "Through the middle sector, lap 6 follows a cleaner line with fewer corrections and a higher minimum corner speed.", "landing.insightExit": "Lap 6 carries more speed out of T4. Earlier throttle preserves the advantage until the next braking zone.", "landing.insightFinal": "The final sector protects the gain without added risk: the delta stabilizes before the finish line.", "landing.unlock": "Analyze your own sessions",
    "landing.liveInsight": "At this point, lap {lap} differs from lap {other} by {speed} km/h with a cumulative delta of {delta} s. Values come from the real Viterbo log.", "landing.demoError": "The Viterbo demo log could not be loaded.",
    "gate.kicker": "MEMBERS ONLY", "gate.title": "Your racing garage", "gate.copy": "Sign in or create an account to connect LapTrace, download telemetry, and analyze sessions.", "gate.button": "Sign in or register",
    "account.kicker": "CLOUD GARAGE", "account.title": "Sign in to LapTrace", "account.copy": "Sign in to open your logs and connect your device.", "account.registerTitle": "Create an account", "account.registerCopy": "Register to connect LapTrace, save logs, and analyze your sessions.", "account.password": "Password", "account.confirmPassword": "Confirm password", "account.passwordMismatch": "Passwords do not match", "account.create": "Create account", "account.working": "Please wait…", "account.signIn": "Sign in", "account.register": "Register", "account.signOut": "Sign out", "account.profile": "Your garage", "account.logs": "Cloud logs: {count}", "account.saved": "Logs saved to the cloud.", "account.confirm": "Check your email to confirm registration.", "account.notConfigured": "Cloud storage has not been configured yet.",
    "nav.analysis": "Analysis", "nav.logs": "Log database", "logsPage.kicker": "CLOUD GARAGE", "logsPage.title": "Your session database", "logsPage.copy": "Every LapTrace log saved to your account. Select a session to open its racing line, laps, and telemetry charts.", "logsPage.back": "Back to analysis", "logsPage.import": "Add log", "logsPage.imported": "The log was added to your account.",
    "status.disconnected": "LapTrace disconnected", "status.searching": "Searching for LapTrace…", "status.connectFailed": "Connection failed",
    "hero.kicker": "LAPTRACE MEMORY ANALYSIS", "hero.title": "Device log.", "hero.accent": "Ready for analysis.", "hero.copy": "Connect after the run, download the recorded telemetry over Bluetooth, and choose a session. No files or manual imports required.",
    "action.connect": "Connect LapTrace", "action.disconnect": "Disconnect LapTrace", "action.start": "Start recording", "action.stop": "Stop recording", "action.download": "Download saved sessions", "action.cancel": "Cancel", "action.unlock": "Unlock",
    "device.gps": "GPS", "device.battery": "Battery", "device.free": "Free", "device.memory": "device memory", "device.used": "Memory used", "device.records": "Records", "device.waiting": "waiting for data", "device.satellites": "{count} satellites", "device.fix": "3D FIX", "device.noFix": "NO FIX", "device.charging": "charging", "device.batteryPower": "on battery", "device.inputVoltage": "input voltage",
    "memory.protected": "Memory is code-protected", "memory.code": "Code", "memory.remaining": "{records} records · ~{time} at 25 Hz", "hint.initial": "The device must be powered on, nearby, and disconnected from the phone.", "hint.mock": "Test BLE adapter is active.",
    "summary.sessions": "Sessions", "summary.loadFirst": "download memory first", "summary.duration": "Duration", "summary.selected": "selected session", "summary.maxSpeed": "Max speed", "summary.frequency": "Sample rate", "unit.speed": "km/h", "unit.hz": "Hz",
    "track.kicker": "TRACK", "track.empty": "No session loaded", "track.slower": "slower", "track.faster": "faster", "track.canvasEmpty": "The LapTrace track will appear here",
    "sessions.kicker": "DEVICE MEMORY", "sessions.title": "Saved sessions", "sessions.empty": "Downloaded recordings will appear here.", "sessions.item": "Session {id}", "sessions.points": "{count} points", "sessions.rename": "Rename", "sessions.delete": "Delete", "sessions.renamePrompt": "Session name", "sessions.deleteConfirm": "Delete “{title}” from the cloud?",
    "telemetry.kicker": "TELEMETRY", "telemetry.speed": "Speed", "telemetry.gforce": "G-FORCES", "telemetry.longitudinal": "Longitudinal G", "telemetry.lateral": "Lateral G", "insights.kicker": "ENGINEERING REVIEW", "insights.title": "What the data shows", "insights.empty": "Download a LapTrace log to generate the initial review.",
    "laps.kicker": "LAPS", "laps.compareTitle": "Lap comparison", "laps.primary": "Primary lap", "laps.compare": "Compare with", "laps.none": "No comparison", "laps.option": "Lap {lap} · {time}", "laps.legend": "Lap {lap}",
    "ai.title": "AI engineer context", "ai.copy": "The app aggregates the selected BLE session: speed, forces, GPS quality, and timing. Raw telemetry stays local.", "ai.placeholder": "For example: which three aspects of this session should I review?", "ai.button": "Copy AI context", "ai.first": "Download and select a session first.", "footer.noData": "No data",
    "progress.preparing": "Preparing…", "progress.records": "{received} / {expected} records", "progress.done": "Done: {count} session(s)",
    "state.connected": "{name} · connected", "state.ready": "{name} · ready", "state.reading": "{name} · reading memory", "state.downloading": "{name} · downloading", "state.loaded": "{name} · data loaded", "state.recording": "{name} · recording", "state.stopped": "{name} · recording stopped", "hint.recording": "Recording to the device memory.", "hint.ready": "Memory ready. Model: {model}.",
    "error.notSelected": "No device selected. Turn on LapTrace, close its phone app, and select LapTrace from the BLE device list.", "error.network": "BLE connection failed. LapTrace may be connected to a phone or another app.", "error.security": "Bluetooth was blocked by the browser. Open the app in Chrome or Edge on localhost.",
    "insight.fastest": "Fastest lap: #{lap}; spread to the slowest lap is {delta} s.", "insight.braking": "Strongest longitudinal deceleration on lap #{lap}: {value} g. The sign depends on device orientation.", "insight.lateral": "Peak lateral load: {value} g on lap #{lap}.", "insight.qualityGood": "Stable stream: {hz} Hz with no gaps longer than {gap} ms.", "insight.qualityBad": "Detected {count} stream gaps; check recording quality.",
  },
  pl: {
    "telemetry.choose": "Wybierz wykres",
    "spec.gpsTitle": "GPS · 25 Hz", "spec.gpsCopy": "GPS, GLONASS, Galileo, BeiDou", "spec.bleCopy": "iOS i Android", "spec.batteryCopy": "do 20 godzin pracy", "spec.usbCopy": "około 3 godz. ładowania", "spec.accelTitle": "Akcelerometr", "spec.gyroTitle": "Żyroskop", "spec.storageTitle": "Pamięć wewnętrzna", "spec.storageCopy": ">2 godz. przy 25 Hz", "spec.splashTitle": "Odporność na zachlapanie", "spec.splashCopy": "deszcz i sporty wodne",
    "landing.kicker": "TELEMETRIA, Z KTÓREJ MOŻESZ KORZYSTAĆ", "landing.title": "Każde okrążenie.", "landing.accent": "Wyjaśnione danymi.", "landing.copy": "LapTrace zapisuje GPS i przeciążenia na torze. Po przejeździe aplikacja synchronizuje log przez Bluetooth, porównuje okrążenia i pokazuje, gdzie został czas.", "landing.cta": "Utwórz darmowe konto", "landing.demoCta": "Zobacz przykładowy log", "landing.proofRate": "precyzyjna telemetria", "landing.proofSensors": "linia i obciążenia", "landing.proofSync": "bez kabli i plików", "landing.demoKicker": "PRAWDZIWY PRZYKŁAD", "landing.demoTitle": "Jeden log. Pełny obraz przejazdu.", "landing.demoCopy": "Sesja demonstracyjna z Circuito di Viterbo pokazuje, jak LapTrace zamienia strumień czujników w czytelne porównanie okrążeń.", "landing.bestLap": "Najlepsze okrążenie", "landing.liveSpeed": "Prędkość kursora", "landing.liveG": "Przeciążenie boczne", "landing.liveDelta": "Bieżąca delta", "landing.compareKicker": "PORÓWNANIE OKRĄŻEŃ", "landing.compareTitle": "Gdzie znaleziono czas", "landing.aiKicker": "ANALIZA AI", "landing.aiTitle": "Dynamiczna analiza", "landing.aiInsight": "Okrążenie 6 ma większą prędkość na wyjściu z T4.", "landing.insightBrake": "Przed T1 okrążenie 6 hamuje później przy stabilnym obciążeniu wzdłużnym. Tutaj zaczyna się przewaga.", "landing.insightMid": "W środkowym sektorze okrążenie 6 ma czystszą linię, mniej korekt i wyższą minimalną prędkość.", "landing.insightExit": "Okrążenie 6 ma większą prędkość na wyjściu z T4. Wcześniejszy gaz utrzymuje przewagę do kolejnego hamowania.", "landing.insightFinal": "W ostatnim sektorze przewaga jest utrzymana bez dodatkowego ryzyka, a delta stabilizuje się przed metą.", "landing.unlock": "Analizuj własne przejazdy",
    "landing.liveInsight": "W tym punkcie okrążenie {lap} różni się od okrążenia {other} o {speed} km/h, a skumulowana delta wynosi {delta} s. Dane pochodzą z prawdziwego logu Viterbo.", "landing.demoError": "Nie udało się wczytać demonstracyjnego logu Viterbo.",
    "gate.kicker": "DOSTĘP DLA UŻYTKOWNIKÓW", "gate.title": "Twój garaż wyścigowy", "gate.copy": "Zaloguj się lub utwórz konto, aby połączyć LapTrace, pobierać telemetrię i analizować sesje.", "gate.button": "Zaloguj lub zarejestruj",
    "account.kicker": "GARAŻ W CHMURZE", "account.title": "Logowanie do LapTrace", "account.copy": "Zaloguj się, aby otworzyć logi i połączyć urządzenie.", "account.registerTitle": "Utwórz konto", "account.registerCopy": "Zarejestruj się, aby łączyć LapTrace, zapisywać logi i analizować sesje.", "account.password": "Hasło", "account.confirmPassword": "Powtórz hasło", "account.passwordMismatch": "Hasła nie są takie same", "account.create": "Utwórz konto", "account.working": "Proszę czekać…", "account.signIn": "Zaloguj", "account.register": "Rejestracja", "account.signOut": "Wyloguj", "account.profile": "Twój garaż", "account.logs": "Logi w chmurze: {count}", "account.saved": "Logi zapisano w chmurze.", "account.confirm": "Sprawdź email, aby potwierdzić rejestrację.", "account.notConfigured": "Chmura nie została jeszcze skonfigurowana.",
    "nav.analysis": "Analiza", "nav.logs": "Baza logów", "logsPage.kicker": "GARAŻ W CHMURZE", "logsPage.title": "Baza twoich przejazdów", "logsPage.copy": "Wszystkie logi LapTrace zapisane na twoim koncie. Wybierz sesję, aby otworzyć linię przejazdu, okrążenia i wykresy telemetrii.", "logsPage.back": "Wróć do analizy", "logsPage.import": "Dodaj log", "logsPage.imported": "Log został dodany do konta.",
    "status.disconnected": "LapTrace rozłączony", "status.searching": "Wyszukiwanie LapTrace…", "status.connectFailed": "Nie udało się połączyć",
    "hero.kicker": "ANALIZA PAMIĘCI LAPTRACE", "hero.title": "Log z urządzenia.", "hero.accent": "Gotowy do analizy.", "hero.copy": "Połącz się po przejeździe, pobierz zapisaną telemetrię przez Bluetooth i wybierz sesję. Bez plików i ręcznego importu.",
    "action.connect": "Połącz LapTrace", "action.disconnect": "Rozłącz LapTrace", "action.start": "Rozpocznij zapis", "action.stop": "Zatrzymaj zapis", "action.download": "Pobierz zapisane sesje", "action.cancel": "Anuluj", "action.unlock": "Odblokuj",
    "device.gps": "GPS", "device.battery": "Bateria", "device.free": "Wolne", "device.memory": "pamięć urządzenia", "device.used": "Zajęta pamięć", "device.records": "Rekordy", "device.waiting": "oczekiwanie na dane", "device.satellites": "Satelity: {count}", "device.fix": "3D FIX", "device.noFix": "BRAK FIX", "device.charging": "ładowanie", "device.batteryPower": "z baterii", "device.inputVoltage": "napięcie wejściowe",
    "memory.protected": "Pamięć zabezpieczona kodem", "memory.code": "Kod", "memory.remaining": "{records} rekordów · ~{time} przy 25 Hz", "hint.initial": "Urządzenie musi być włączone, znajdować się w pobliżu i nie być połączone z telefonem.", "hint.mock": "Aktywny jest testowy adapter BLE.",
    "summary.sessions": "Sesje", "summary.loadFirst": "najpierw pobierz pamięć", "summary.duration": "Czas", "summary.selected": "wybrana sesja", "summary.maxSpeed": "Prędkość maks.", "summary.frequency": "Częstotliwość", "unit.speed": "km/h", "unit.hz": "Hz",
    "track.kicker": "TOR", "track.empty": "Brak wczytanej sesji", "track.slower": "wolniej", "track.faster": "szybciej", "track.canvasEmpty": "Tutaj pojawi się tor z pamięci LapTrace",
    "sessions.kicker": "PAMIĘĆ URZĄDZENIA", "sessions.title": "Zapisane sesje", "sessions.empty": "Pobrane nagrania pojawią się tutaj.", "sessions.item": "Sesja {id}", "sessions.points": "{count} punktów", "sessions.rename": "Zmień nazwę", "sessions.delete": "Usuń", "sessions.renamePrompt": "Nazwa sesji", "sessions.deleteConfirm": "Usunąć „{title}” z chmury?",
    "telemetry.kicker": "TELEMETRIA", "telemetry.speed": "Prędkość", "telemetry.gforce": "PRZECIĄŻENIA", "telemetry.longitudinal": "Przeciążenie wzdłużne", "telemetry.lateral": "Przeciążenie boczne", "insights.kicker": "ANALIZA INŻYNIERSKA", "insights.title": "Co pokazują dane", "insights.empty": "Pobierz log LapTrace, aby utworzyć wstępną analizę.",
    "laps.kicker": "OKRĄŻENIA", "laps.compareTitle": "Porównanie okrążeń", "laps.primary": "Główne okrążenie", "laps.compare": "Porównaj z", "laps.none": "Bez porównania", "laps.option": "Okrążenie {lap} · {time}", "laps.legend": "Okrążenie {lap}",
    "ai.title": "Kontekst dla inżyniera AI", "ai.copy": "Aplikacja agreguje wybraną sesję BLE: prędkość, przeciążenia, jakość GPS i czas. Surowe dane pozostają lokalnie.", "ai.placeholder": "Na przykład: które trzy aspekty tej sesji warto sprawdzić?", "ai.button": "Kopiuj kontekst AI", "ai.first": "Najpierw pobierz i wybierz sesję.", "footer.noData": "Brak danych",
    "progress.preparing": "Przygotowanie…", "progress.records": "{received} / {expected} rekordów", "progress.done": "Gotowe: {count} sesji",
    "state.connected": "{name} · połączono", "state.ready": "{name} · gotowy", "state.reading": "{name} · odczyt pamięci", "state.downloading": "{name} · pobieranie", "state.loaded": "{name} · dane pobrane", "state.recording": "{name} · trwa zapis", "state.stopped": "{name} · zapis zatrzymany", "hint.recording": "Trwa zapis do pamięci urządzenia.", "hint.ready": "Pamięć gotowa. Model: {model}.",
    "error.notSelected": "Nie wybrano urządzenia. Włącz LapTrace, zamknij aplikację w telefonie i wybierz LapTrace z listy BLE.", "error.network": "Połączenie BLE nie powiodło się. LapTrace może być połączony z telefonem lub inną aplikacją.", "error.security": "Bluetooth został zablokowany przez przeglądarkę. Otwórz aplikację w Chrome lub Edge na localhost.",
    "insight.fastest": "Najszybsze okrążenie: #{lap}; różnica do najwolniejszego wynosi {delta} s.", "insight.braking": "Najsilniejsze opóźnienie wzdłużne na okrążeniu #{lap}: {value} g. Znak zależy od orientacji urządzenia.", "insight.lateral": "Maksymalne przeciążenie boczne: {value} g na okrążeniu #{lap}.", "insight.qualityGood": "Stabilny strumień: {hz} Hz, bez przerw dłuższych niż {gap} ms.", "insight.qualityBad": "Wykryto {count} przerw w strumieniu; sprawdź jakość nagrania.",
  },
};

let language = "ru";
try {
  const saved = localStorage.getItem("d3-language");
  const browser = navigator.language?.slice(0, 2);
  language = SUPPORTED_LANGUAGES.includes(saved) ? saved : SUPPORTED_LANGUAGES.includes(browser) ? browser : "ru";
} catch {}

const listeners = new Set();
export const getLanguage = () => language;
export function t(key, values = {}) {
  const template = translations[language]?.[key] ?? translations.ru[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`);
}
export function applyTranslations(root = typeof document !== "undefined" ? document : null) {
  if (!root) return;
  document.documentElement.lang = language;
  root.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = t(element.dataset.i18n); });
  root.querySelectorAll("[data-i18n-placeholder]").forEach((element) => { element.placeholder = t(element.dataset.i18nPlaceholder); });
  const selector = root.querySelector("#languageSelect");
  if (selector) selector.value = language;
}
export function setLanguage(next) {
  if (!SUPPORTED_LANGUAGES.includes(next)) return;
  language = next;
  try { localStorage.setItem("d3-language", next); } catch {}
  applyTranslations();
  listeners.forEach((listener) => listener(next));
}
export function onLanguageChange(listener) { listeners.add(listener); return () => listeners.delete(listener); }
